server:
    port: 9401

spring:
  application:
    name: binglian-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos


  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
  redis:
      database: 0
      port: 6379
      host: localhost
      password: 
management:
  endpoints:
    web:
      exposure:
          include: "*"