## 启动顺序： #1

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/simple_mall?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
#  redis:
#    database: 0
#    host: localhost
#    port: 6379

mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: tb_   # 数据库表名的前缀
  type-aliases-package: com.binglian.entity  # 实体类所在包
  mapper-locations: classpath*:/mapper/**Mapper.xml   # xml文件所在位置


server:
  port: 2001
